### PR TITLE
Isoimg kc

### PR DESCRIPTION
**Pull request by krishnachaganti**
Initial version for Review

@codrcodz

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -1,2 +1,35 @@
 # piedpiper-pakman-faas
 Function for packaging up various artifacts into a single archive for storage and/or delivery.
+# make sure to insall
+  pip3 install PyYAML
```
Comment (codrcodz) [inline README.md]: Works fine with Python 3.7.3. The `pathlib` module in the standard library in this version works fine:
```
codz@dt:~/projects/piedpiper-pakman-faas$ $(which python3.7) --version
Python 3.7.3
codz@dt:~/projects/piedpiper-pakman-faas$ $(which pip3.7) --version
pip 19.0.3 from /home/codz/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip (python 3.7)
codz@dt:~/projects/piedpiper-pakman-faas$ pip3.7 freeze | grep -oP "(pathlib|PyYAML).*"
PyYAML==5.1
codz@dt:~/projects/piedpiper-pakman-faas$ python3.7 isoimage.py sample.yml 
 Statred Processing :sample.yml
Image name: customer.iso
Image type: iso
unarchive the files to destination: target/src
unarchive the files to destination: target/docs
 Generating Iso image mkisofs  -V CDNAME -J -r -o customer.iso target
I: -input-charset not specified, using utf-8 (detected in locale settings)
Using CERTI000.PDF;1 for  target/src/test_tar/Certificate (3).pdf (Certificate (2).pdf)
Using CERTI001.PDF;1 for  target/src/test_tar/Certificate (2).pdf (Certificate (1).pdf)
Using __CER000.PDF;1 for  target/src/test_tar/._Certificate (3).pdf (._Certificate (1).pdf)
Using CERTI002.PDF;1 for  target/src/test_tar/Certificate (1).pdf (Certificate.pdf)
Using __CER001.PDF;1 for  target/src/test_tar/._Certificate (1).pdf (._Certificate (2).pdf)
Using __CER002.PDF;1 for  target/src/test_tar/._Certificate (2).pdf (._Certificate.pdf)
Using ITINE000.PDF;1 for  target/docs/Itinerary_ Raleigh.pdf (Itinerary_ Flight to New Orleans.pdf)
Using RECEI000.PDF;1 for  target/docs/Receipt for Flight to New Orleans.pdf (Receipt for Raleigh.pdf)
Using __ITI000.PDF;1 for  target/docs/__MACOSX/._Itinerary_ Raleigh.pdf (._Itinerary_ Flight to New Orleans.pdf)
Using __REC000.PDF;1 for  target/docs/__MACOSX/._Receipt for Flight to New Orleans.pdf (._Receipt for Raleigh.pdf)
 84.58% done, estimate finish Wed May 29 10:18:33 2019
Total translation table size: 0
Total rockridge attributes bytes: 3654
Total directory bytes: 15038
Path table size(bytes): 102
Max brk space used 23000
5916 extents written (11 MB)
```

Not so much with Python 3.5 (Ubuntu 16.04 LTS default), looks like the builtin `pathlib` module doesn't have all the same attributes as the newer module:
```
codz@dt:~/projects/piedpiper-pakman-faas$ $(which python3) --version
Python 3.5.2
codz@dt:~/projects/piedpiper-pakman-faas$ $(which pip3) --version
pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)
codz@dt:~/projects/piedpiper-pakman-faas$ pip3 freeze | grep -oP "(pathlib|PyYAML).*"
PyYAML==5.1
codz@dt:~/projects/piedpiper-pakman-faas$ python3 isoimage.py sample.yml 
 Statred Processing :sample.yml
Image name: customer.iso
Image type: iso
Traceback (most recent call last):
  File "isoimage.py", line 151, in <module>
    sys.exit(main(sys.argv[1:]))
  File "isoimage.py", line 56, in main
    shutil.copy2(file, target_directory)
  File "/usr/lib/python3.5/shutil.py", line 250, in copy2
    dst = os.path.join(dst, os.path.basename(src))
  File "/usr/lib/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'PosixPath' object has no attribute 'rfind'
```

Works fine in 3.6.0 though:
```
codz@dt:~/projects/piedpiper-pakman-faas$ pyenv install 3.6.0
Downloading Python-3.6.0.tar.xz...
-> https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
Installing Python-3.6.0...
Installed Python-3.6.0 to /home/codz/.pyenv/versions/3.6.0
codz@dt:~/projects/piedpiper-pakman-faas$ pyenv local 3.6.0
codz@dt:~/projects/piedpiper-pakman-faas$ $(which pip3) --version
pip 9.0.1 from /home/codz/.pyenv/versions/3.6.0/lib/python3.6/site-packages (python 3.6)
codz@dt:~/projects/piedpiper-pakman-faas$ $(which python3) --version
Python 3.6.0
codz@dt:~/projects/piedpiper-pakman-faas$ pip3 install PyYAML
Collecting PyYAML
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/9f/2c/9417b5c774792634834e730932745bc09a7d36754ca00acf1ccd1ac2594d/PyYAML-5.1.tar.gz
Installing collected packages: PyYAML
  Running setup.py install for PyYAML ... done
Successfully installed PyYAML-5.1
codz@dt:~/projects/piedpiper-pakman-faas$ python3 isoimage.py sample.yml 
 Statred Processing :sample.yml
Image name: customer.iso
Image type: iso
unarchive the files to destination: target/src
unarchive the files to destination: target/docs
 Generating Iso image mkisofs  -V CDNAME -J -r -o customer.iso target
I: -input-charset not specified, using utf-8 (detected in locale settings)
Using CERTI000.PDF;1 for  target/src/test_tar/Certificate (3).pdf (Certificate (2).pdf)
Using CERTI001.PDF;1 for  target/src/test_tar/Certificate (2).pdf (Certificate (1).pdf)
Using __CER000.PDF;1 for  target/src/test_tar/._Certificate (3).pdf (._Certificate (1).pdf)
Using CERTI002.PDF;1 for  target/src/test_tar/Certificate (1).pdf (Certificate.pdf)
Using __CER001.PDF;1 for  target/src/test_tar/._Certificate (1).pdf (._Certificate (2).pdf)
Using __CER002.PDF;1 for  target/src/test_tar/._Certificate (2).pdf (._Certificate.pdf)
Using ITINE000.PDF;1 for  target/docs/Itinerary_ Raleigh.pdf (Itinerary_ Flight to New Orleans.pdf)
Using RECEI000.PDF;1 for  target/docs/Receipt for Flight to New Orleans.pdf (Receipt for Raleigh.pdf)
Using __ITI000.PDF;1 for  target/docs/__MACOSX/._Itinerary_ Raleigh.pdf (._Itinerary_ Flight to New Orleans.pdf)
Using __REC000.PDF;1 for  target/docs/__MACOSX/._Receipt for Flight to New Orleans.pdf (._Receipt for Raleigh.pdf)
 84.58% done, estimate finish Wed May 29 10:30:22 2019
Total translation table size: 0
Total rockridge attributes bytes: 3654
Total directory bytes: 15038
Path table size(bytes): 102
Max brk space used 23000
5916 extents written (11 MB)
```

Recommend dropping a few lines in near the top to detect this and exit if someone attempts it: 
```
if sys.version_info[0] != 3 or sys.version_info[1] < 6:
    print("This script requires Python version 3.6+")
    sys.exit(1)
```

That should yield this type of behavior:
```
codz@dt:~/projects/piedpiper-pakman-faas$ pyenv local system 
codz@dt:~/projects/piedpiper-pakman-faas$ $(which python3) --version
Python 3.5.2
codz@dt:~/projects/piedpiper-pakman-faas$ python3 isoimage.py sample.yml 
This script requires Python version 3.6+
```

File: isoimage.py [hunk 2]
```diff
@@ -0,0 +1,151 @@
+import yaml
```
Comment (codrcodz) [inline isoimage.py:1]: The script itself appears to be functioning as designed. I did some rudimentary smoke testing. Good job!
```
codz@dt:~/projects/piedpiper-pakman-faas$ \
comm -3 \
  <(cd ~/projects/piedpiper-pakman-faas/target/; find ./ | sort) \
  <(cd /mnt/iso; find ./ | sort)
```
Looks like the output in `target/` properly matches the contents of the ISO. Also looks like the mock data combined with the instructions in your `sample.yaml` yield the expected results:

```
codz@dt:~/projects/piedpiper-pakman-faas$ tree /mnt/iso
/mnt/iso
├── bin
│   ├── binary1.zip
│   ├── binary2.tar
│   └── deps
├── docs
│   ├── Itinerary_ Flight to New Orleans.pdf
│   ├── Itinerary_ Raleigh.pdf
│   ├── logs
│   ├── __MACOSX
│   ├── Notification of Foreign Travel.doc
│   ├── Receipt for Flight to New Orleans.pdf
│   └── Receipt for Raleigh.pdf
├── README.MD
└── src
    └── test_tar
        ├── Certificate (1).pdf
        ├── Certificate (2).pdf
        ├── Certificate (3).pdf
        └── Certificate.pdf
```
Looks like it is still lacking some error handling in places, for instance, I didn't create the file called `ci-cd_pipeline_output.log` in my `logs/` directory initially, and it quietly skipped it. When the user explicitly requests a file by name, it might be best to throw an exception when nothing is present in those cases. Or, it might even be nice to let the user specify whether or not is allowed to match nothing, even for regex. Thoughts @ragingpastry ?

**Review by codrcodz — COMMENTED** [review]
Added some feedback. @ragingpastry , you should take a look and see if your happy with the internals before @krishnachaganti finalizes his testing.

File: isoimage.py [hunk 3]
```diff
@@ -0,0 +1,151 @@
...
+            #print('should Unarchive:',unarhive)
+            if unarhive :
+               unarhive_file_to_destination(destination, file_name)
+            else:
+                #print('Copy file to destination')
+                py = pathlib.Path().glob(file_name)
+                for file in py:
+                    shutil.copy2(file, destination)
+
+def unarhive_file_to_destination(destination, file_name):
```
Comment (ragingpastry) [inline isoimage.py]: Should be unarchive_file_to_destination. This will have to be fixed in other places too

**Review by ragingpastry — CHANGES_REQUESTED** [review]
Looks good so far. Let's make sure this passes a default "flake8" run and add some additional error handling. It would be useful to first validate that the configuration file is correct before attempting to parse it for example. 

The logic seems sound. Let's get this passing with flake8 and some more validation checks though

**Comment by krishnachaganti** [comment]
ran flake8 on files and results
flake8 isoimage.py 
(env) [15:23] [~/gct/piedpiper-pakman-faas] (ISOIMG_KC)

File: isoimage.py (hunk 3 above)
Comment (krishnachaganti) [reply isoimage.py]: fixed in this push 
97c1590

File: isoimage.py (hunk 2 above)
Comment (krishnachaganti) [reply isoimage.py:1]: added new function validate_yaml_file(data_loaded) that verifies all the files in the yaml status and exits if it does not find one in this push 97c1590

**Comment by krishnachaganti** [comment]
after creating we should delete the temp target directory or should leave it for debugging purpose?

**Comment by ragingpastry** [comment]
We can leave the temp target directory around. The invocation of this tool will happen in the context of a temporary directory so it will go away when the context is left.

**Review by ragingpastry — APPROVED** [review]
